<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-CIBJPLA" name="via.Login" tests="12" failures="0" timestamp="2021-10-04T16:05:16 IST" time="121.857" errors="1">
  <testcase name="tc_01" time="18.176" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_10" time="52.422" classname="via.Login">
    <error type="java.lang.IllegalArgumentException" message="Cannot find elements when the XPath is null.">
      <![CDATA[java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.
at org.openqa.selenium.By$ByXPath.<init>(By.java:339)
at org.openqa.selenium.By.xpath(By.java:92)
at via.Login.tc_10(Login.java:162)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tc_10 -->
  <system-out/>
  <testcase name="tc_03" time="3.189" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_04" time="3.182" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_06" time="3.502" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_08" time="2.559" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_09" time="4.630" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_07" time="2.606" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_02" time="6.419" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_11" time="8.834" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_12" time="12.320" classname="via.Login"/>
  <system-out/>
  <testcase name="tc_05" time="4.018" classname="via.Login"/>
  <system-out/>
</testsuite> <!-- via.Login -->
